### ISSUE TITLE
Composer fork

### ISSUE THREAD

**Issue by WGPSenshi** [funiq/geoPHP#1]
Looks like this is the currently most active and up-to-date fork of geoPHP. Thanks for trying to keep geoPHP alive :) .
Would you mind indexing it as its own version for composer/ packagist? It would only require changing your composer.json to use funiq/geoPHP instead of phayes. That way everyone else could comfortably load your updated fork without unnecessary hurdles.

**Comment by BathoryPeter** [comment]
I would be happy if Phayes/geoPHP come back to life and we can use and improve that well known and loved project.
I will try to talk to Patrick again. As long as I get some answer I don't want to move towards an independent fork.

**Comment by teohhanhui** [comment]
Thanks for doing this!

As a short term measure, you can delete the irrelevant tags and branches to speed up `composer update` (as I've requested here but it was probably lost in the sea of emails: https://github.com/phayes/geoPHP/pull/125#issuecomment-236492237)

**Comment by teohhanhui** [comment]
Also, you might want to do something about https://github.com/BathoryPeter/geoPHP :laughing:

I think many people may accidentally end up there from your PR...

**Comment by BathoryPeter** [comment]
Thanks for the suggestions, just deleted BathoryPeter/geoPHP!
I have already deleted automatically imported tags, branches and releases about a month ago :)

**Comment by SrihariThalla** [comment]
Hey, nice work!

Have you heard back from Patrick? It would be really good to merge the fork or even break out and update Composer to use `funiq/geoPHP` (worst case scenario!)

**Comment by d0nk3y** [comment]
Bump!  Any word from Patrick?  If he still doesn't get back to you, would you consider turning this into your own thing with actual releases?  I'm tempted to use your fork, but I agree that it would be best to get your work moved into the original.  Tough call.

**Comment by BathoryPeter** [comment]
Hi All!
Sorry for the late response.

I couldn't contact Patrick in the last two years, so I just updated composer.json and submitted the project to Packagist. Feel free to use this fork (and send pull requests :)

**Comment by danhunsaker** [comment]
We'll need version tags, too, so that we can install it without needing dev stability. :slightly_smiling_face:
