### ISSUE TITLE
Invalid annotatnion `@returns`

### ISSUE THREAD

**Issue by Niiph** [funiq/geoPHP#10]
https://github.com/funiq/geoPHP/blob/facd8fbb0656a9c7b862870ef9fe5a4a865ae25e/src/Geometry/Polygon.php#L195

There's annotation `@returns` instead of `@return`, it crashes my app.

**Comment by BathoryPeter** [comment]
Thanks for reporting!
I plan to release a new minor version with PHP 8.3 support in the few days.
