### ISSUE TITLE
[question] Version tagging

### ISSUE THREAD

**Issue by tomvo** [funiq/geoPHP#2]
Great work in keeping this fork alive in a more modern structure. Would you mind adding some tags so we don't have to load from the master branch?

**Comment by Dicebar** [comment]
@BathoryPeter Any chance of marking the current version as stable?

**Comment by BathoryPeter** [comment]
I have a great news for you 🥳
A few days ago I released [v2.0](https://github.com/funiq/geoPHP/releases/tag/v2.0.0) and working on 2.1.
Any help would be appreciated.

**Comment by Dicebar** [comment]
That's great, thanks!
