### ISSUE TITLE
php 8.1 support

### ISSUE THREAD

**Issue by tomvo** [funiq/geoPHP#4]
We're moving to PHP 8.1 and would appreciate a php 8.1 build. It might already work out of the box, in that case we would need an updated composer version. 
Thanks.

**Comment by BathoryPeter** [comment]
This was my intention in v2.0.1, but it seems I incorrectly set PHP version in composer.json. Thank you for pointing that out!

I released v2.0.2:
https://github.com/funiq/geoPHP/releases/tag/v2.0.2
