### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by SkyspotEmil** [funiq/geoPHP#7]
Any plans on releasing a version with PHP 8.2?

Thanks for a great package :)

**Comment by albig** [comment]
I would appreciate to use a new release of funiq/geoPHP with PHP 8.2 support. Is there anything, I can do? The PR #8 shows that no code changes are necessary, right?

**Comment by BathoryPeter** [comment]
Just released 2.0.3. The only change was to enable PHP 8.2.
